name: Build Executables
run-name: Creating executables from python script
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile accounting-docs-script.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/accounting-docs-script

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile accounting-docs-script.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-executable
          path: dist/accounting-docs-script

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
        continue-on-error: true
      
      - name: Build executable
        run: pyinstaller --onefile accounting-docs-script.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/accounting-docs-script.exe
